### PR TITLE
Add support for Expenses

### PR DESCRIPTION
**Pull request by yaqwsx**

### CODE REVIEW

**Comment by piit79** [comment]
Thanks for the contribution! Just pulled this into my fork and wrote a simple parser/importer for Zasilkovna PDF invoices and Czech Post PDF posting receipts (via pdftotext) so that they can be imported into Fakturoid automatically. Works like a charm!

**Comment by yaqwsx** [comment]
Would you mind sharing your scripts for parsing Czech Post PDF invoices? I was thinking about doing the same.

**Comment by piit79** [comment]
@yaqwsx Sure, here's the repo: https://github.com/piit79/expense2fakturoid-py

Please keep in mind this is a result of one night's coding and half a day's cleaning up :) It works for me™ on the few Zasilkovna invoices and Czech Post receipts I tested it with, but YMMV. If you encounter any problems, please file a GitHub issue. Thanks!

**Comment by farin** [comment]
diky

**Pull request merged**
